### ISSUE TITLE
Problem with CN

### ISSUE THREAD

**Issue by stormwin** [Dexus/pem#100]
Hi,

I have a problem with certification information. (function readCertificateInfo)
CN field come out with emailAddress together
like this: CERTIFICATE TEST, emailAddress=test@test.com
and also, email field is empty.
I do not have a problem with certificate which contains CN without space in it

**Comment by Dexus** [comment]
i will have a look into this issue.

**Comment by bausmeier** [comment]
We are experiencing the same issue with pem@1.10.0.

**Comment by stormwin** [comment]
I switched to x509

**Comment by Dexus** [comment]
Will fixed in tomorrow.

**Comment by Dexus** [comment]
can you please try again or if not fixed please send the cert that makes problems?

**Comment by bausmeier** [comment]
@Dexus The latest version fixes the issue. Thanks a lot 🎉

**Comment by Dexus** [comment]
You are welcome
