### ISSUE TITLE
Calling an asynchronous function without callback is deprecated - fs.unlinkSync()

### ISSUE THREAD

**Issue by ilyash** [Dexus/pem#103]
Hi.

Downstream: https://github.com/beameio/beame-sdk/issues/20

https://github.com/Dexus/pem/blob/46de22cdbd9b8a0c7117753751c9974668e0f4b6/lib/pem.js#L1029

> `fs.unlinkSync(file.path)`

Should use callback now (in node 7)

**Comment by Dexus** [comment]
Update your pem version! 

It is already fixed.
