### ISSUE TITLE
What is the difference between Service key and Client Key

### ISSUE THREAD

**Issue by TargetFocussed** [Dexus/pem#108]
What is the difference between Servicekey and Client Key ?

In case of client certificates should I use client key ?.

**Comment by Dexus** [comment]
ServiceKey: private Key to sign the client certificate
ClientKey: the private Key to use for the client certificate

Please read there for https://github.com/Dexus/pem#create-a-certificate-signing-request and https://github.com/Dexus/pem#create-a-certificate
