### ISSUE TITLE
Document return values

### ISSUE THREAD

**Issue by fresheneesz** [Dexus/pem#114]
The API docs in the readme are much harder to understand without specifying the return values of these functions. What properties are in those return values and what do they mean? Can you please document that?

**Comment by Dexus** [comment]
I think its good documented, when you wish a better doc you are welcome to update it.

**Comment by fresheneesz** [comment]
@Dexus I'm a bit confused by your response. I'm not saying the documentation is bad, or that the way you document return values is bad. I'm saying that you aren't documenting return values *at all*. If you can point me to where you think the return values are documented, maybe I can spend some time improving their visibility or understandabilty. So .. where are the return values documented?
