### ISSUE TITLE
Cannot create ssl on windows

### ISSUE THREAD

**Issue by betimer** [Dexus/pem#115]
Cannot work on windows, the error log is below:

Error: Invalid openssl exit code: 1
% openssl req -new -sha256 -subj /CN=localhost -key C:\Users\Xin\AppData\Local\Temp\1f2827703aaded33c9074fede3f3877d5c718079
WARNING: can't open config file: /etc/ssl/openssl.cnf
Unable to load config info from /etc/ssl/openssl.cnf

**Comment by kaue** [comment]
Try using the option `csrConfigFile`
