### ISSUE TITLE
Make ca parameter in verifySigningChain optional

### ISSUE THREAD

**Issue by basbossink** [Dexus/pem#117]
When using the `verifySigningChain` function and leaving the `ca` parameter `undefined`, the pem module passes an empty temporary file to openssl in the `-CAFile` parameter, causing it to report an error. Since the `-CAFile` parameter is optional it would be nice if the `ca` parameter of the `verifySigningChain` function can be left `undefined` as well.

If interested I would be willing to submit a pull request to implement this enhancement.

**Comment by Dexus** [comment]
A PR is allways welcome.

**Comment by basbossink** [comment]
Nice, I'll try to move this forward. I have adjusted the production code, I still have to fix a number of tests to complete the PR.
