### ISSUE TITLE
PEM file

### ISSUE THREAD

**Issue by baloian** [Dexus/pem#118]
How can I extract public key (secp256k1) from PEM file and format it to 32-byte buffer ?
Is it possible ?

**Comment by KaiSchwarz-cnic** [comment]
Not sure if this is what you're looking for, but
```bash
npm install node-forge
```
```javascript
pem.getPublicKey(key, function(error, data) {
    if (!error)
        console.log(data.publicKey);
});
```

Have an eye on `node-forge` which provides a lot functionality around tls / ssh etc. including working with Buffers.
