### ISSUE TITLE
Tips on NET::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by binarykitchen** [Dexus/pem#123]
Probably this has been answered before but I couldn't find any answers. When I use something like this for local development

```
gulp.task('connect', ['build'], function (cb) {
  pem.createCertificate({days: 1, selfSigned: true}, function (err, keys) {
    if (err) {
      cb(err)
    } else {
      plugins.connect.server({
        port: 4300,
        debug: true,
        livereload: true,
        https: {
          key: keys.serviceKey,
          cert: keys.certificate
        },
...
```

and open Chrome with https://localhost:4300 it complains about NET::ERR_CERT_AUTHORITY_INVALID and have to click on `Proceed to localhost (unsafe)` each time.

I think this can be skipped by importing a certain file into Chrome but with the above snipped this is not doable.

Probably I am missing something here? Any clues? Thanks

**Comment by Dexus** [comment]
Unless you create a "root-certificate" that signs the dev cert. You can't do anything.
