### ISSUE TITLE
Feature Request: add checking / debugging possibility / convert DER to PEM

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [Dexus/pem#126]
See: section "Checking Using OpenSSL" and "Debugging Using OpenSSL"
https://www.sslshopper.com/article-most-common-openssl-commands.html

I really like your library and would prefer to continue using your module for that purpose instead of having the need to code it myself around. Just because you encapsulated already everything in a very nice way.

Furthermore, as you support readPkcs12, it would be great if you could also provide a method readDER which provides the contents converted as PEM format.

Also removing a passphrase from private key file appears in the above article, which could be of interest for someone.

**Comment by Dexus** [comment]
Hello @papakai when you need it quickly, you are welcome to contribute and open a Pull Request.

I will add it to my ToDo.

**Comment by KaiSchwarz-cnic** [comment]
Hi @Dexus,

Is there a way to through your methods to pipe a result of one openssl command to another one?
`openssl x509 -noout -modulus -in certificate.crt | openssl md5`
I haven't found a way, but maybe I'm not deep enough dived into code.
If not, would you mind if I introduce a new dependency `md5` instead? imo overhead as openssl provides that functionality, but if piping is not supported...

Cheers 
Kai

**Comment by KaiSchwarz-cnic** [comment]
See my PR here: https://github.com/Dexus/pem/pull/127
I have not covered everything and finally ended in using the md5 library for the above mentioned piping.

Hope you like the PR.
