### ISSUE TITLE
Feature Request: add 'altNames' to readCertificateInfo

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [Dexus/pem#129]
We need also access to 'altNames' in the parsed data structure.
Currently we're using a mixture of npm module 'x509' and 'pem' to cover all our needs.
Parsing for 'altNames' is the last thing which keeps 'x509' as dependency in our project.

Let me know your opinion on this @Dexus. Is readCertificateInfo the right place to also return this? In which way should that data exactly be returned then (object key name + substructure)?
I can try to work on that too in my PR.

**Comment by Dexus** [comment]
yes readCertificateInfo is the right place. i would use `san` for altNames and also in the same way as of the create csr where you also can use san with IP and DNS.

If you have an other idea I'm open to it.

**Comment by KaiSchwarz-cnic** [comment]
I've recognized `san`, but wasn't sure if `san` is always present when `altNames` is and if `san` covers all possibilities of `altNames`. Maybe you have an deeper insight here? Going for some lecture in the meanwhile, maybe `san` is simply what we need. Thanks for pointing to it.

**Comment by KaiSchwarz-cnic** [comment]
Thanks again, I think `san` is what we need. Closing this issue.
