### ISSUE TITLE
openssl -rand option not available on Alpine/LibreSSL

### ISSUE THREAD

**Issue by tkurki** [Dexus/pem#132]
Alpine has switched from OpenSSL to LibreSSL, which no longer supports -rand option and certificate generation fails with these params https://github.com/Dexus/pem/blob/master/lib/pem.js#L62

Is specifying the randomness source strictly required there? Both OpenSSL and LibreSSL work without it. 

In my case, generating a ssl certificate upon first startup of a Docker container I doubt how random /var/log/mail:/var/log/messages are.

**Comment by Dexus** [comment]
Hi I'm already fix it local and will push it with a other fix.

Von meinem iPhone gesendet
