### ISSUE TITLE
pem now seems to need dirty-chai, but isn't getting it

### ISSUE THREAD

**Issue by bajacondor** [Dexus/pem#144]
After updating to pem 1.11.0, I run my tests and they fail due to dirty-chai not being found.  I traced it back to a transitive dependency of pem.  Yet pem doesn't seem to load it.

**Comment by Dexus** [comment]
did you `npm i` in your own tests?

**Comment by KaiSchwarz-cnic** [comment]
if you did `npm  i`:
any software test should run in development area, and should not be available on production area. This then also includes the availability of packages used for automated tests like dirty-chai / chai / mocha / cross-env / nyc etc. 
This means, only in case environment variable `NODE_ENV` is not set or is set to `development`, then npm will install these packages.

**Comment by bajacondor** [comment]
Yes, I am running `NODE_ENV=development npm install`
And my test script also sets the NODE_ENV variable.
I am running Node v 8.5.0, npm v 5.3.0
 This behavior seems to have just started with the upgrade of pem 1.11.0

**Comment by bajacondor** [comment]
Actually, the problem seems to be that the pem tests are attempting to run when I run my tests...  My test script runs with this command:
`"test-unit": "NODE_ENV=development nyc --reporter=html ./node_modules/.bin/mocha './**/*.spec.js'"`
Why would pem tests be running in this case?

**Comment by KaiSchwarz-cnic** [comment]
I am sure, the problem is your npm script glob. `'./**/*.spec.js'` also includes all *.spec.js files in node_modules folder. You can find ways here: https://github.com/mochajs/mocha/issues/1577
