### ISSUE TITLE
code review for test_build_openssl.sh

### ISSUE THREAD

**Issue by KaiSchwarz-cnic** [Dexus/pem#152]
see: https://github.com/koalaman/shellcheck

can be done via command line `shellcheck test_build_openssl.sh`

or via

Atom editor plugin: [linter-shellcheck](https://github.com/AtomLinter/linter-shellcheck)

or online via

https://www.shellcheck.net/

... low priority, just making things more standardized.

**Comment by Dexus** [comment]
Fix via 5150c87

**Comment by Dexus** [comment]
It is not very often edited, so I don't see why we should add any checks to the package.

Maybe we can create a Wiki-Page that lists best plugins for Atom, etc.

**Comment by KaiSchwarz-cnic** [comment]
My intention was only to get the file reviewed and to point to the atom editor plugin which is very helpful :-)
Thanks for having cared about it. Sorry that my explanation wasn't very helpful and misleading^^
