### ISSUE TITLE
Change default options for future usage

### ISSUE THREAD

**Issue by Dexus** [Dexus/pem#16]
Hi Andris (@andris9),

what do you think about to change the default settings for:

**keyBitsize** - should maybe now set to 2048 as default for CSR because the most CAs require a min. keysize of 2048.
**hash** - should maybe now set to sha256 as default for CSR because the most CAs beginn to change to sha256 hash. 
### Background:

Microsoft has, however, decided to replace the hashing mechanism SHA-1 in favor of a more modern and safer. One has the SHA-256 mechanism selected as one of the four mechanisms of SHA-2 will come to this use.

The first date on the roadmap is the 16th January 2016 provided. On that date Microsoft terminated the trust in code-signing certificates issued by this mechanism. More dates are the 1st January 2017 the trust is to be withdrawn with the all SSL certificates with SHA-1 mechanism.

Therefore, GlobalSign has decided to implement the beginning of March 2014 standard in issuing new certificates SHA 256.

**Comment by andris9** [comment]
In generally I'm in favor of these changes as these should not break anything already existing. Keysize should definitely be set to 2048 bits. I'm not so certain about moving away from SHA-1 but I guess this should be done anyway at one point sooner or later, so I guess this is OK too. 

Could you make a pull request with these changes, so I could upgrade the version and publish it?

**Comment by Dexus** [comment]
Yes i will make a pull request. But first i will work on https://github.com/andris9/pem/issues/14 so that EV Certs can be fetched.

**Comment by Dexus** [comment]
https://github.com/andris9/pem/pull/17
