### ISSUE TITLE
Does not seem to respect config path directive

### ISSUE THREAD

**Issue by MJCD** [Dexus/pem#173]
I'm on windows so the path structure's very different. I tried;

```
pem.config(
  {
    pathOpenSSL: 'C://Program Files (x86)//GnuWin32//bin//openssl',
    config: 'C://Program Files (x86)//GnuWin32//share//openssl.cnf',
  },
);
pem.createCertificate(
  {
    days: 1,
    selfSigned: true,
    config: 'C://Program Files (x86)//GnuWin32//share//openssl.cnf',
  },
  (err, keys) => { /* ... */ }
);
```
**Resulting error**

> Unable to load config info from /usr/local/ssl/openssl.cnf

**Comment by MJCD** [comment]
It should just pass config: '...' to openssl afaik.

**Comment by MJCD** [comment]
Alternatively as a quick fix for now - is it possible to just disable a config file at all (as its currently all default values anyway) and I can just use `pem.config`  as normal without it failing on the file read attempt? :)

**Comment by Dexus** [comment]
best way on windows is to place the openssl.cnf in the same directory as openssl... I don't understand why it will not open on your system... on my system I have often the problem with this path and I need to install it to the root path. Also you you can set a system environment with the openssl config link.

example:
`set OPENSSL_CONF=c:\[PATH TO YOUR OPENSSL DIRECTORY]\bin\openssl.cfg`

Good doc for this: https://www.tbs-certificates.co.uk/FAQ/en/openssl-windows.html

**Comment by Dexus** [comment]
Btw. i like the Idear to set per pem.config the default openssl.cnf file, so you dont need it extra set it on the other commands.

**Comment by MJCD** [comment]
Even putting the `openssl.cnf` file in `./bin/` from `./shared/` (which is default on Windows for a Gnu32 install) - it still fails looking for the same file.

It appears there is some location where the path is perhaps hardcoded or failing over from windows paths to a default hardcoded linux path or somesuch.

**Comment by MJCD** [comment]
I might create a PR - if you can provide any guidance as to where this might occur in the codebase.

**Comment by MJCD** [comment]
I couldn't find anything responsible in your code so I believe its possibly an openssl thing when nothing is specified. I found this which doesn't appear to actually pass anything in but i'm not too sure

https://github.com/Dexus/pem/blob/master/lib/pem.js#L110-L118

**Comment by Dexus** [comment]
What for a openssl version for windows do you use? All i found recommend by openssl works as excepted.

Von meinem iPhone gesendet

**Comment by MJCD** [comment]
I was using Gnu32's implementation @
http://gnuwin32.sourceforge.net/packages/openssl.htm

However I see now the recommended version is @
https://slproweb.com/products/Win32OpenSSL.html

So I will try again with that.

- Michael

**Comment by MJCD** [comment]
So, some progress after switching to using the correct windows openssl
implementation - however it's still having issues. I am using a sample
config file (from http://web.mit.edu/crypto/openssl.cnf) and get the
following..

My code:
pem.config(
{
pathOpenSSL: 'C:\\OpenSSL-Win64\\bin\\openssl.exe',
config: path.resolve('./openssl.config'),
},
);
pem.createCertificate(
{
days: 1,
selfSigned: true,
config: path.resolve('./openssl.config'), // just in my project directory
resolved to absolute path
},
(err, keys) => {
if (err) {
logger.log('error', 'Failed to create PEM for https');
logger.log('error', err);
process.exit(1);
} else {
const secureServer = https.createServer(
{ cert: keys.certificate, key: keys.serviceKey },
app,
).listen(443);
const secureSocketServer = io(secureServer);
}
},
);


Result:
[Running] node "c:\Projects\_NEX\demo\src\app.js"
error: Failed to create PEM for https {}
error: Error: Invalid openssl exit code: 1
% openssl x509 -req -sha256 -days 1 -in
C:\Users\MJCD\AppData\Local\Temp\af972ab3ffebfdda4d18848c7d62ea8616738bae
-signkey
C:\Users\MJCD\AppData\Local\Temp\01b71b62db100e606590db98e56813fe03f89653
-extensions v3_req -extfile
C:\Users\MJCD\AppData\Local\Temp\fc6f495bd786d89a9a22d070e196d95f6822a149
x509: Error on line 1 of config file
"C:\Users\MJCD\AppData\Local\Temp\fc6f495bd786d89a9a22d070e196d95f6822a149"
{}

[Done] exited with code=1 in 0.771 seconds

**Comment by MJCD** [comment]
So, some progress after switching to using the correct windows openssl
implementation - however it's still having issues. I am using a sample
config file (from http://web.mit.edu/crypto/openssl.cnf) and get the
following..

(sorry something messed up with the styling in email >.>)

Node version 8.7.0 on Windows 10 

My code:
```
pem.config(
{
pathOpenSSL: 'C:\\OpenSSL-Win64\\bin\\openssl.exe',
config: path.resolve('./openssl.config'),
},
);
pem.createCertificate(
{
days: 1,
selfSigned: true,
config: path.resolve('./openssl.config'), // just in my project directory
resolved to absolute path
},
(err, keys) => {
if (err) {
logger.log('error', 'Failed to create PEM for https');
logger.log('error', err);
process.exit(1);
} else {
const secureServer = https.createServer(
{ cert: keys.certificate, key: keys.serviceKey },
app,
).listen(443);
const secureSocketServer = io(secureServer);
}
},
);
```


Result:
```
[Running] node "c:\Projects\_NEX\demo\src\app.js"
error: Failed to create PEM for https {}
error: Error: Invalid openssl exit code: 1
% openssl x509 -req -sha256 -days 1 -in
C:\Users\MJCD\AppData\Local\Temp\af972ab3ffebfdda4d18848c7d62ea8616738bae
-signkey
C:\Users\MJCD\AppData\Local\Temp\01b71b62db100e606590db98e56813fe03f89653
-extensions v3_req -extfile
C:\Users\MJCD\AppData\Local\Temp\fc6f495bd786d89a9a22d070e196d95f6822a149
x509: Error on line 1 of config file
"C:\Users\MJCD\AppData\Local\Temp\fc6f495bd786d89a9a22d070e196d95f6822a149"
{}
```

**Comment by MJCD** [comment]
Just tried the sample config provided from your recommended url source above (https://www.tbs-certificates.co.uk/openssl-dem-server-cert-thvs.cnf) but the same result.

**Comment by Dexus** [comment]
We dont support yet `pem.config({config:'path/to/config')` so you need to pass the config on the command that support it...

it looks like your config is wrong. You need to fix the config to your needs look: 
`RANDFILE		= $ENV::HOME/.rnd`
```
[ CA_default ]

dir		= ./demoCA		# Where everything is kept
certs		= $dir/certs		# Where the issued certs are kept
crl_dir		= $dir/crl		# Where the issued crl are kept
```
....

**Comment by MJCD** [comment]
In this second config im now using from your recommended link (https://www.tbs-certificates.co.uk/openssl-dem-server-cert-thvs.cnf)

See line 43

Note as well, the error is not specified to be in the config file but some temporary generated file. Does your transform expect those beginning global definitions eg lines 11-23 need to be moved inside that container or.. ?

**Comment by Dexus** [comment]
try to read the config file and use the content as the config variable on the options. IIRC it was read before and used as content of the generated file.

**Comment by MJCD** [comment]
So you mean like:

Now:
```
config: path.resolve('./openssl.config')
```

After:
```
config: fs.readFileSync(path.resolve('./openssl.config'))
```

inside `pem.createCertificate()` yeah?

**Comment by Dexus** [comment]
right, can be right... i'm curently not sure.

**Comment by MJCD** [comment]
That totally resolved it. Thank you very much. I will play further from here ^_^

**Comment by Dexus** [comment]
Thx, I think we should add a switch, for that... but good to know where the problem comes from.

**Comment by Dexus** [comment]
**TODO**: add new Option to pem.config for global openssl.conf, add option to the commands to provide a File Path and not only the content...

**Comment by KaiSchwarz-cnic** [comment]
also documenting this makes a lot sense i think
