### ISSUE TITLE
checkCertificate returns true on invalid CSR

### ISSUE THREAD

**Issue by Djalmar** [Dexus/pem#195]
When validating a CSR the method checkCertificate misses stderr error from 
openssl.spawnWrapper method. Which is causing a TRUE response on an invalid CSR

openssl.js
`spawn(params, binary, function (err, code, stdout, stderr) {
    helper.deleteTempFiles(delTempPWFiles, function (fsErr) {
      callback(err || fsErr, code, stdout, stderr)
    })
  })`

pem.js (error2 is the missing argument in which an openssl validation error is returned)
`  openssl.spawnWrapper(params, certificate, function (sslErr, code, stdout,error2) {
`

Sorry for the bad english

**Comment by Dexus** [comment]
@Djalmar should be fixed, can you check again?

**Comment by Dexus** [comment]
Close due to no answer.
