### ISSUE TITLE
Example Usage

### ISSUE THREAD

**Issue by konsumer** [Dexus/pem#2]
Thanks for making pem!

Took me a minute to work out how to use it for simple self-signed key HTTPS, thought I might give you examples for your docs. These are both valid for 1 day, and require root perms for the low port (https standard 443).
## Basic https

``` javascript
var https = require("https"),
    pem = require('pem');

pem.createCertificate({days:1, selfSigned:true}, function(err, keys){
    https.createServer({key: keys.serviceKey, cert: keys.certificate}, function(req, res){
        res.end("o hai!")
    }).listen(443);
});
```
## Express

``` javascript
var https = require("https"),
    pem = require('pem'),
    express = require('express');

pem.createCertificate({days:1, selfSigned:true}, function(err, keys){
    var app = express();

    app.get('/',  requireAuth, function(req, res){
        res.send("o hai!");
    });

    https.createServer({key: keys.serviceKey, cert: keys.certificate}, app).listen(443);
});
```

**Comment by andris9** [comment]
If you'd create a pull request, I'd happily add this to the docs (Y)

**Comment by konsumer** [comment]
Sweet! Already have forked for adding native support (#3), do you have a preferred method for adding the changes back in? As I understand it, it will keep updating the fork when I push to it.

**Comment by andris9** [comment]
i can checkout only specific files (eg. readme.md) from your fork, so it doesn't matter if you change other files as well

**Comment by konsumer** [comment]
Cool. submitted.
