### ISSUE TITLE
Windows support without adding openssl to PATH

### ISSUE THREAD

**Issue by gabegorelick** [Dexus/pem#20]
Contrary to [popular belief](https://github.com/andris9/pem/issues/5), this module actually  seems to work fine on Windows. So :+1: for that! However, you do have to add `openssl` to your PATH, which is a minor inconvenience. 

It'd be nice if node-pem fell back to the default Windows directories (`C:/OpenSSL-Win64` or `C:/OpenSSL-Win32`), similar to [how ursa does it](https://github.com/Medium/ursa/blob/master/binding.gyp#L12).

**Comment by gabegorelick** [comment]
I can work on a pull request if you think you'd be interested in this.

**Comment by andris9** [comment]
yeah, sounds reasonable, if you'd create a PR for this, I'll pull

**Comment by fresheneesz** [comment]
What would be even better is if openSSL was installed if it doesn't exist already

**Comment by scaret** [comment]
+1

I'll be glad if `pem` has method to choose which openssl to use.

**Comment by floatdrop** [comment]
This is closed by https://github.com/andris9/pem/commit/113a207b371a1b85899d2de0326c3c5bb1e1c8d4

**Comment by gabegorelick** [comment]
There's a typo in that commit that makes it fail. You're setting
pathOpenSSL to itself instead of options.pathOpenSSL.

**Comment by floatdrop** [comment]
@andris9 nah, `pathOpenSSL` is [scoped variable](https://github.com/andris9/pem/blob/master/lib/pem.js#L9), that can be [set by `config` method](https://github.com/andris9/pem/blob/master/lib/pem.js#L362).

**Comment by gabegorelick** [comment]
Closing since there's now an API for specifying the path to the binary.
