### ISSUE TITLE
CA signing example?

### ISSUE THREAD

**Issue by theogravity** [Dexus/pem#21]
Hi there! May I ask for a sample regarding how to create a certificate if you have a root CA and key that was generated?

**Comment by theogravity** [comment]
Figured it out after digging into the code:

```
pem.createCertificate({
    serviceCertificate: ca_root_cert, //string
    serviceKey: ca_root_key, //string
    serial: Date.now(),
    days: 500,
    country: "",
    state: "",
    locality: "",
    organization: "",
    organizationUnit: "",
    commonName: servername
}, function (err, keys) {

  //Context will appear as empty, but it does have the 'info'
  crypto.createCredentials({
      key: keys.clientKey,
      cert: keys.certificate,
      ca: ca_root_cert
  }).context
})
```

**Comment by scaret** [comment]
I've also figured it out from the package source code. I should have a look at `Issues` list first!

It seems that the document is not complete.

**Comment by lllama** [comment]
Worth noting that serviceCertificate and serviceKey need to be the file contents, rather than file names. (Might have been obvious if I'd paid enough attention).

**Comment by floatdrop** [comment]
~~Thanks for the example! But how do I generate `ca_root_cert` with pem?~~

`ca_root_cert` and `ca_root_key` can be also generated with `pem.createCertificate`.
