### ISSUE TITLE
Documentation website not working

### ISSUE THREAD

**Issue by MaxvandeLaar** [Dexus/pem#210]
Hi, 

It seems that the api docs website [https://www.deineagentur.com/projects/pem](https://www.deineagentur.com/projects/pem) is no longer working.

![image](https://user-images.githubusercontent.com/5842932/45020306-e4e50a80-b02e-11e8-8b77-6806c91b5bbf.png)

**Comment by Dexus** [comment]
Should work again.

**Comment by evanmosby** [comment]
Hi,

Looks like the doc website is down again
