### ISSUE TITLE
pem.createPkcs12 can not export CA cert to a PKCS12 keystore

### ISSUE THREAD

**Issue by guoyibj** [Dexus/pem#216]
pem.createPkcs12 can not export CA cert to a PKCS12 keystore using below option setting: 
options = { certFiles: ['ca.pem', 'intermediate_ca.pem']}

**Comment by Dexus** [comment]
Hello @guoyibj apology for the late reply:

I see the problem: You need to merge both files and then add them as options parameters as a file array.

options = { certFiles: ['intermediate_ca+ca.pem']}

This should work.
