### ISSUE TITLE
Better error message if openSSL doesn't exist on the system

### ISSUE THREAD

**Issue by fresheneesz** [Dexus/pem#22]
You get a cryptic error message from spawn if your system doesn't have openssl. It would be nice if an error message was given back that said something to the effect of "pem requires openssl to be installed".

**Comment by andris9** [comment]
You probably get `"Invalid openssl exit code: 127"` as the error message. Code 127 is a standard code for a missing command.

You can check the existence of openssl command with this command:

```
openssl version > /dev/null 2>&1 || echo 'Warning: openssl command not found'
```

You can add this command to your package.json file as "install" script:

```
{
    ...
    "scripts": {
        "test": "....",
        "install": "openssl version > /dev/null 2>&1 || echo 'Warning: openssl command not found'"
    }
    ...
}
```

I do not want to bake the checks into the module as it would have to cover all supported platforms (linux / windows) and there's no point adding such overhead

**Comment by fresheneesz** [comment]
@andris9 

A. the whole point of making modules like this is so people don't have to write relevant code like this in every single one of their own modules. This module is the perfect place to put your suggestion, ESPECIALLY because it would have to cover all supported platforms. Solve it once, solve it forever. Why force hundreds of people to rewrite the code over and over again (or more likely, simply not have a good error message)

B. What overhead? The code you wrote is incredibly cheap to run.
