### ISSUE TITLE
How to create a cert chain with PEM

### ISSUE THREAD

**Issue by RameshRM** [Dexus/pem#221]
I am trying to create cert chaing with Root -> Intermediate -> End Cert, The support with the module using `serviceCertificate & serviceKey` doesnt work very well and not able to create the chain, Can anyone help me with this ?

**Comment by Dexus** [comment]
Have a look here: https://github.com/Dexus/pem/blob/610a403fef97ad6fcea0b8f6ce2d7d5160eb9f16/test/pem.spec.js#L616-L667
