### ISSUE TITLE
CreateCertificate should support altName as options

### ISSUE THREAD

**Issue by abizake** [Dexus/pem#227]
The document mentions the following 

> :- Note that createCertificate and createCSR supports the altNames option which would be easier to use in most cases

But in the implementation , only CreateCSR supports altNames and createCertificate does not. 
Having support of altNames in craeteCertificate helps generating certificate with dynamic alt names .
please advise.

**Comment by Dexus** [comment]
With the upcomming release 1.14.0 we will support CreateCertificate with SAN CSR.

And you are right, with 1.14.1 I will fix it...
