### ISSUE TITLE
Additional genrsa option support

### ISSUE THREAD

**Issue by jcottr** [Dexus/pem#23]
`createPrivateKey()` only takes one option (`keyBitsize`), while [`genrsa`](https://www.openssl.org/docs/apps/genrsa.html) offers many additional options; most commonly used are:
- encryption cipher (e.g. `des3`, `aes256`)
- encryption password

I would fork and patch, but it looks like the current implementation is very permissive about the type of `keyBitsize`, so I worry that any change I would make might break some existing clients. I could prepare a patch that expects an `options` object instead of `keyBitsize`, but I think we'd need to rev the major version. Is that something you're okay with?

**Comment by andris9** [comment]
I don't have any preferences as long as it doesn't break existing clients. You could add an optional argument that includes the new params and if the argument is missing it wouldn't be used – this would keep old clients running but would allow to use the new stuff.

**Comment by Dexus** [comment]
@jcottr 
tomorrow i will look at this and add optional param for encryption and password.

**Comment by Dexus** [comment]
#48 - can now be closed
