### ISSUE TITLE
Error with creating certificate with a serviceKeyPassword

### ISSUE THREAD

**Issue by pvangeepuram** [Dexus/pem#233]
The latest version of the library throws error when trying to create certificate with a service key password.  

1550075835165 - Origin: Worker (PID 165)
worker_1          |    [Error] TypeError: Cannot read property 'push' of undefined
worker_1          |     at Object.module.exports.createPasswordFile (/app/node_modules/pem/lib/helper.js:78:21)
worker_1          |     at /app/node_modules/pem/lib/pem.js:406:16
worker_1          |     at fetchCertificateData (/app/node_modules/pem/lib/pem.js:1206:3)
worker_1          |     at /app/node_modules/pem/lib/pem.js:547:12
worker_1          |     at /app/node_modules/pem/lib/openssl.js:222:7
worker_1          |     at deleteSeries (/app/node_modules/pem/lib/helper.js:130:14)
worker_1          |     at myCallback (/app/node_modules/pem/lib/helper.js:121:18)

**Comment by Dexus** [comment]
thanks for your PR its merged and release is done.
