### ISSUE TITLE
I want to get this tweak but don't understand how to get the windows application to work :(

### ISSUE THREAD

**Issue by ng4ever** [Dexus/pem#268]
Is it just me or is it just to far over my head ? Should I give up ?

I tried. 

If anyone could help that would be great but if not that is great too!

**Comment by Dexus** [comment]
@ng4ever you should use a windows binary of openssl like from https://slproweb.com/products/Win32OpenSSL.html and set the config to the path of the binary.

**Comment by Dexus** [comment]
something like:

```js
pem.config({
pathOpenSSL:"....pathto/openssl.exe"
});
```
