### ISSUE TITLE
Generate certificate with hash algorithm sha256

### ISSUE THREAD

**Issue by scaret** [Dexus/pem#27]
I'm on windows 8, and the default hash method for my OpenSSL certificate generating is `sha1`, which is not secure any more. So I'll get a certificate warning when I use Chrome to visit the node-pem-signed HTTPS site

https://code.google.com/p/chromium/issues/detail?id=401365

I suggest to use sha256 to create certificate, which means calling `openssl x509 -req -sha256 ...` in `pem.createCertificate()`

![png](https://cloud.githubusercontent.com/assets/454201/5373092/00b52dc4-808d-11e4-9ded-102a7268a9af.png)
![png1](https://cloud.githubusercontent.com/assets/454201/5373098/0717c7f8-808d-11e4-9b81-093860f87319.png)

**Comment by Dexus** [comment]
@andris9 can be closed! Is allready done...
