### ISSUE TITLE
Is this package allows to convert certificate file?

### ISSUE THREAD

**Issue by pelim95** [Dexus/pem#270]
I found the convert module in the API Documentation but could not find a way to access to it to use the method inside. I would like to do a PFX to PEM conversion on the certificate.
Thanks if anyone can help on this!

**Comment by Dexus** [comment]
```js

const pem = require('pem');

pem.convert.PEM2DER(....)
```

Have Fun!

**Comment by pelim95** [comment]
Thanks!
