### ISSUE TITLE
Avoid using stdin

### ISSUE THREAD

**Issue by jonnius** [Dexus/pem#271]
I want to use pem to check whether a cert belongs to a key by comparing their modulus on a server. If the key is encrypted, the `getModulus` call prompts for the password on stdin (on my server, causing it to freeze). How can I tell the pem module to never use stdin / never let openssl use stdin (e.g. by setting stdin to `/dev/null`)?

**Comment by Dexus** [comment]
I think it had already fixed, but if not here is the [docs](https://dexus.github.io/pem/jsdoc/module-pem.html#.getModulus)
