### ISSUE TITLE
Link to API Documentation is dead

### ISSUE THREAD

**Issue by jonnius** [Dexus/pem#281]
The link https://www.deineagentur.com/projects/pem/index.html that can be found in the README and on [npmjs.com](https://www.npmjs.com/package/pem) is dead. Is the  API Documentation no more or is it located elsewhere?

**Comment by jonnius** [comment]
Was this closed by accident without an answer?

**Comment by Dexus** [comment]
Closed because i change the doc url and upload it: https://dexus.github.io/pem/jsdoc/

**Comment by jonnius** [comment]
Great. Thanks!
