### ISSUE TITLE
Enhance README: highlight the openssl dependency

### ISSUE THREAD

**Issue by keksipurkki** [Dexus/pem#301]
Hi,

You could help out developers adopting your library by making it clearer in your README that the heavy lifting is done by openssl CLI and that this requires you to access disk. 

I'm bringing this up as we are developing Dockerized servers with minimal runtimes. On them, openssl is not automatically available and disk IO is slow / disk space is limited. 

Best regards,
Elias Toivanen

**Comment by Dexus** [comment]
I will add a notice. Thank you!

Best Regards, Josef
