### ISSUE TITLE
readPkcs12 returns CA as main cert

### ISSUE THREAD

**Issue by eanders-ms** [Dexus/pem#302]
My pfx contains two CAs and the primary certificate. When I pass it to `readPkcs12` to extract them, the function returns one of the CAs in the `cert` field of the key bundle. Looking at the implementation, I believe the issue is here:

https://github.com/Dexus/pem/blob/5e88b2056f5e5edb43e1ada7a0b015dbc7f59da6/lib/pem.js#L817-L818

The main cert is the last entry in the array, not the first, so this should read:
```js
        keybundle.cert = certs.pop()
        keybundle.ca = certs
```

Thanks for writing this super useful utility!

**Comment by Dexus** [comment]
can you provide a fixture? because it will break the current tests.

**Comment by Dexus** [comment]
After checking the OpenSSL results, I cannot confirm that there is a bug. According to what I have seen in the tests, everything is correct. If this is not the case, just open a new ticket and attach an example of an appropriate PKCS12 file.
