### ISSUE TITLE
sha256 support (and make it default)

### ISSUE THREAD

**Issue by taoeffect** [Dexus/pem#31]
sha1 is going away soon and discouraged: http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html

This is related to #27.

Needed:
- Generate cert with sha256 (done in PR #29)
- Return fingerprint (see [this comment](https://github.com/andris9/pem/pull/29#issuecomment-66866664))

**Comment by scaret** [comment]
@taoeffect it sounds good to support sha256 fingerprint. 

But for a certificate, it can use sha256 for signature hash algorithm, at the same time using sha1 for thumbprint algorithm. For now, https certificate for github.com is using this

![png](https://cloud.githubusercontent.com/assets/454201/5430704/adf32e4c-8451-11e4-9509-f5e7f0e00f9c.png)
![png](https://cloud.githubusercontent.com/assets/454201/5430709/c2ff6b98-8451-11e4-9b5c-103a03dc87ad.png)

If github.com uses sha1 in this way, I think it's not so urgent to change the default algorithm for fingerprint.

Unlike `pem.createCertificate()`, `pem.getFingerprint()` doesn't have an option field for hash method. This means if we want a sha256 version `getFingerprint()`, we have to either change the API, or change the default hash algorithm. For the latter one, If some existing project is using `pem`, they will find after updating the node module, their old fingerpints will not match the new ones. So it's really a big change for the function.

**Comment by Dexus** [comment]
SHA2 ist default it you dont give some other hash as option. This is for CSR and CERTs.
For the Fingerprint, your right, there needs some options to fix.

**Comment by Dexus** [comment]
@andris9 can be closed! Is allready done... see https://github.com/andris9/pem/pull/47

Now fingerprint is default sha1 but can also use sha256, sha384 etc.
