### ISSUE TITLE
Passphrase

### ISSUE THREAD

**Issue by gagle** [Dexus/pem#34]
Have you considered the option to allow self-signed certificates with a passphrase?

**Comment by andris9** [comment]
Not really but if you'd create a pull request that does this **AND** does not break the current API, I'd pull it. This module does everything I already need, so I'm not really interested in developing it forward myself.

**Comment by DullReferenceException** [comment]
Created this to support the feature: https://github.com/andris9/pem/pull/49

**Comment by Dexus** [comment]
_reminder_
Need to add passphrase to all function that need it for privatekeys

**Comment by debonair** [comment]
Has anyone made a pull request for this?

**Comment by Dexus** [comment]
hi @debonair
yes but not for all functions that need it now.
