### ISSUE TITLE
Stream support?

### ISSUE THREAD

**Issue by noamokman** [Dexus/pem#35]
Any plans to enable stream for some of the [gulp](https://github.com/gulpjs/gulp) lovers out here?
It would be nice to stream the certificates to the file system or as [vinyl](https://github.com/wearefractal/vinyl) files.

**Comment by andris9** [comment]
The entire module is about wrangling with the openssl command and regexing output from openssl stdout so no plans to add streaming. Besides there's no point to stream anyway – the certificates are so small they do not even reach the buffering watermark which by default is 16kB.
