### ISSUE TITLE
'npm install' installs v1.14.7 without 'lib' folder

### ISSUE THREAD

**Issue by L-Shenkai** [Dexus/pem#359]
Running 'npm install pem' installs pem v1.14.7 without 'lib' folder as seen in the attached pic. Meanwhile directly downloading v1.14.7 from here contains the missing 'lib' folder.

Is this an npm issue or did I miss any steps in documentation. I wanted to use the 'convert' file inside the 'lib' folder.

![Pem Issue](https://user-images.githubusercontent.com/20699357/235208694-d3198025-4245-4952-a7ca-6419bacbc3c9.png)

**Comment by Dexus** [comment]
v1.14.8 will contain the lib folder
