### ISSUE TITLE
Catch spawn errors

### ISSUE THREAD

**Issue by noamokman** [Dexus/pem#37]
If an error occurred at the open ssl spawn function it is uncaught,
Happens when I run it without admin permissions on windows.

I think we should add this:

``` js
  openssl.on('error', function (err) {
    callback(err);
  });
```

at the spawnOpenSSL function, but I didn't PR because I'm not sure if you wanna wrap the exception or not.

**Comment by andris9** [comment]
It does makes sense to add this. Returning the error object is fine. Do you also get the 'exit' or 'close' events on error or not?

**Comment by noamokman** [comment]
only the close event is being fired after the error event.
I'll PR the fix with regard to the bothDone function.
