### ISSUE TITLE
Use node-which

### ISSUE THREAD

**Issue by noamokman** [Dexus/pem#40]
Hi!
I think we should be using [node-which](https://github.com/isaacs/node-which) in order to detect if the user has openssl and it is accessible.

I thought about something like this:

``` js
var which = require('which');
which('openssl', function(error, path){
if(error){
  // Handle no open ssl
}

// All good
});
```

**Comment by andris9** [comment]
Good idea :+1:

**Comment by noamokman** [comment]
I'll PR :+1:
