### ISSUE TITLE
dhparam generation

### ISSUE THREAD

**Issue by silverwind** [Dexus/pem#45]
I think it would be a nice feature to have in this module. The function should return the output of `openssl dhparam -outform PEM [numbits]`, with `numbits` configurable (default 512).

Docs: https://www.openssl.org/docs/apps/dhparam.html

**Comment by Dexus** [comment]
i like your idea. I will create the function tomorrow and make the PR.

**Comment by Dexus** [comment]
@andris9 can now be closed by PR #47

**Comment by silverwind** [comment]
Awesome, I'll try this soonish.

**Comment by Dexus** [comment]
@silverwind :+1:

**Comment by silverwind** [comment]
Working great, thanks!

**Comment by Dexus** [comment]
:+1:
