### ISSUE TITLE
[security] genrsa -rand improperly used

### ISSUE THREAD

**Issue by taoeffect** [Dexus/pem#46]
Edit: Not sure if [this](https://github.com/andris9/pem/blob/2cd2135f6b5f9c8414147ebe991ef1345fd5e6cf/lib/pem.js#L38-L42) is OK:

``` javascript
var params = ['genrsa',
    '-rand',
    '/var/log/mail:/var/log/messages',
    keyBitsize
];
```

Do these files need to have a good source of entropy?

The [docs](https://www.openssl.org/docs/apps/genrsa.html) refer to this as a seed for the random number generator. I'm not what openssl does with these files internally, so it's probably safer to not include that option.

**Comment by Dexus** [comment]
hey @taoeffect 
the rand option load the file (or the files in the directory) into the random number generator.

but you can also use rng-tools to get better /dev/urandom data. its only to get better results of the key, for some reason of bad keygens....
