### ISSUE TITLE
Add serviceKeyPassword option for createCertificate

### ISSUE THREAD

**Issue by kousha-icracked** [Dexus/pem#54]
Similar to `createCSR` where you can pass `clientKeyPassword` as an `option` to automatically use the password without prompting for it, it would be amazing to have the capability for `pem.createCertificate` and that we could pass the `serviceKeyPassword` and prevent the prompt from the terminal.

**Comment by petersunquest** [comment]
I just plus some code to pem.js. Then I can use a password private key to create createCertificate.

183            'commonName = Common Name',
184            'commonName_max = 64',
185        ].join('\n'));
186    }
+
-   var passwordFilePath = null;
-    if (options.clientKeyPassword) {
-        passwordFilePath = pathlib.join(tempDir, crypto.randomBytes(20).toString('hex'));
-        fs.writeFileSync(passwordFilePath, options.clientKeyPassword);
-        params.push('-passin');
-        params.push('file:' + passwordFilePath);
-   
-    }

188    execOpenSSL(params, 'CERTIFICATE REQUEST', tmpfiles, function(error, data) {
189       if (passwordFilePath) {
190            fs.unlink(passwordFilePath);
191        }

**Comment by Dexus** [comment]
an option is added.
