### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by OstlerDev** [Dexus/pem#58]
Hi there! I am loving your module and I use it in one of my applications, however I am running into an issue when some people attempt to generate a certificate using this on Windows (as can be seen here: https://github.com/OstlerDev/PopcornTV/issues/11 )

I am getting a response that it gives the error that certificate is undefined. My source code where I am using your module can be found here: https://github.com/OstlerDev/PopcornTV/blob/master/atv.js#L8

Is there something I am doing that would cause this to not work on Windows?

Thanks,
OstlerDev

**Comment by Mithgol** [comment]
I've tried to run the following script on Windows:

``` javascript
require('pem').createCertificate({days:1, selfSigned:true}, function(err, keys){
   console.log('Err:');
   console.log(err);
   console.log('Keys:');
   console.log(keys);
});
```

and I've got the following result in my console:

```
Err:
[Error: Could not find openssl on your system on this path: openssl]
Keys:
undefined
```

It means that `pem` module actually uses OpenSSL.

**Comment by Mithgol** [comment]
[Line 675](https://github.com/andris9/pem/blob/9e23b9266194a11b26aae5c966b5a2d023fd02c2/lib/pem.js#L675) of `pem.js` indicates that `pem` currently expects that
- either the full path to the `openssl` binary is [given in `pem.config`](https://github.com/andris9/pem/blob/9e23b9266194a11b26aae5c966b5a2d023fd02c2/README.md#setting-openssl-location),
- or the full path to the `openssl` binary is given in the `OPENSSL_BIN` variable of the system's environment,
- or the `openssl` binary can be called just as `openssl` (i.e. it resides in a directory listed in the system's `PATH` variable).

**Comment by Mithgol** [comment]
The most simple workaround is to download and unpack http://indy.fulgan.com/SSL/openssl-1.0.2d-i386-win32.zip (or another [OpenSSL for Windows](https://www.openssl.org/related/binaries.html)) and either put OpenSSL to the system's `PATH` or use [`pem.config`](https://github.com/andris9/pem/blob/9e23b9266194a11b26aae5c966b5a2d023fd02c2/README.md#setting-openssl-location) as the method to let `pem` know of the OpenSSL's location.

**Comment by ghost** [comment]
There is another issue (at least on my Windows Machine) where openssl is incapable of finding a configuration file. The Error Message states:

Invalid openssl exit code: 1
% openssl req -new -sha256 -subj /CN=localhost -key C:...\AppData\Local\Temp\15fd9efb5fc6f1c8253f1ee552e605bb8fb637d4
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
Unable to load config info from /usr/local/ssl/openssl.cnf

There is no configuration file at this location. The file is located in the same path as the openssl.exe file.

**Comment by Mithgol** [comment]
I can reproduce this issue on my Windows as well. Seems like a bug in a Windows build of OpenSSL.

**Comment by andris9** [comment]
I created an example app that bundles openssl.exe with all required files, you can find the code [here](https://bitbucket.org/andris9/node-win32-openssl/src). In this case you do not need to have openssl installed on the system.

**Comment by ghost** [comment]
This works just fine. To be honest i didnt even know that you could change the enviroment variables of the node process... good to know.

Thanks you very much!

Best regards

Michael

**Comment by silverwind** [comment]
How about including a postinstall script that checks for the presence of OpenSSL and downloads it if needed? Would that be in scope of this module?

**Comment by basarat** [comment]
Perhaps mention the dependency on OpenSSL up front.

**Comment by astra137** [comment]
I ran into problems with OpenSSL Light in my user and system PATH on Node v5.5.0, NPM v3.3.12, Windows 10 Pro x86_64.

It was resolved by allowing `pem` to install the latest version of `which`. Perhaps package.json should be updated and pushed to NPM.

**Comment by Mithgol** [comment]
@maccelerated Good idea. Would you create a pull request?

**Comment by mikemaccana** [comment]
If you're using the Shining Light Productions openssl binaries, see also #97

**Comment by tkarls** [comment]
I also had problem with not finding the openssl.cnf on windows. I solved by setting the following env variable.
OPENSSL_CONF="my path"

**Comment by mahdipakravan-dev** [comment]
> I've tried to run the following script on Windows:
> 
> ```js
> require('pem').createCertificate({days:1, selfSigned:true}, function(err, keys){
>    console.log('Err:');
>    console.log(err);
>    console.log('Keys:');
>    console.log(keys);
> });
> ```
> 
> and I've got the following result in my console:
> 
> ```
> Err:
> [Error: Could not find openssl on your system on this path: openssl]
> Keys:
> undefined
> ```
> 
> It means that `pem` module actually uses OpenSSL.

Use Gitbash To Run . 
This is Worked For Me :)
