### ISSUE TITLE
Options

### ISSUE THREAD

**Issue by 3goats** [Dexus/pem#6]
I can't seem to see what options I can provide when creating a CSR. I would like to be able to add some additional extensions to the CSR.

BTW - Your code seems to work fine on Windows!

Regards,

**Comment by mattsawyer77** [comment]
check out line ~79 of pem.js:

``` javascript
        var params = ["req",
                      "-new",
                      "-" + (options.hash || "sha1"),
                      "-subj",
                      generateCSRSubject(options),
                      "-key",
                      "--TMPFILE--"
                      ];
```

**Comment by Dexus** [comment]
@andris9 can you close this "issue"?
