### ISSUE TITLE
Certificate routines:X509_check_private_key: key values mismatch

### ISSUE THREAD

**Issue by dYb** [Dexus/pem#64]
I have met a problem `Certificate routines:X509_check_private_key: key values mismatch`,
by some searching ,I fount it maybe a problem of openssl.
but I dont find how to solute it,
any suggestions?

**Comment by Dexus** [comment]
Can you give more details? Only to say i have a problem "..." don't realy helpful.
When you geht this error?

**Comment by dYb** [comment]
Here is detail, At the beginning everything worked well, then I changed my network between WAL and wifi, after that, the error shows up.

**Comment by Dexus** [comment]
Its no PEM related issue.

**Comment by dYb** [comment]
Ok, I think there is some one who has met with this problem, thanks all the same
