### ISSUE TITLE
Uncaught TypeError: pem.readPkcs12 is not a function

### ISSUE THREAD

**Issue by jonniespratley** [Dexus/pem#65]
The latest tagged version does not have this method.

**Comment by Dexus** [comment]
oh, i dont updated the npm ...

**Comment by nwanglu** [comment]
Is this fixed yet on NPM?

**Comment by asakaev** [comment]
There is no readPkcs12 in 1.8.1 from npm.

**Comment by DavidBeale** [comment]
Any word on a new npm release for this? Thanks.

**Comment by Dexus** [comment]
Update in npm uploaded.

**Comment by DavidBeale** [comment]
Thats great, thanks
