### ISSUE TITLE
Handling serial numbers

### ISSUE THREAD

**Issue by AlexGustafsson** [Dexus/pem#66]
How do I handle serial numbers when signing CSRs with a CA in a sensible way?
When I used bare OpenSSL i used `-CAcreateserial` which did the work for me.

**Comment by Dexus** [comment]
Hi,

you can doing it with serviceCertificates (https://github.com/andris9/pem/blob/master/lib/pem.js#L300-L326) or via config files

**Comment by AlexGustafsson** [comment]
So if I supply a serviceCertificate it should be all set?

**Comment by Dexus** [comment]
Look to the source code and use a config file.
