### ISSUE TITLE
TypeError: Cannot read property 'on' of undefined

### ISSUE THREAD

**Issue by armellarcier** [Dexus/pem#68]
`pem.readCertificateInfo` crashes the app

```
at node_modules/pem/lib/pem.js:835:23
at node_modules/pem/lib/pem.js:1002:9
at node_modules/pem/node_modules/which/which.js:82:18
at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by Dexus** [comment]
On witch version of node?

Von meinem iPhone gesendet

**Comment by armellarcier** [comment]
v0.12.2

**Comment by Dexus** [comment]
@Benew it looks like you dont use the last version of `pem`, is it correct?

**Comment by Dexus** [comment]
@Benew 
I only get a similar error when I use a incorrect certificate / CSR .

**Comment by armellarcier** [comment]
I'm using NPM version (1.8.1).

Is there a way to catch that error? Incorrect certificates are a real use case for me.
