### ISSUE TITLE
node-xmpp and regression

### ISSUE THREAD

**Issue by sonnyp** [Dexus/pem#72]
Hey @andris9 

This may not be an issue directly with pem module but your input/help would be greatly appreciated.
A while ago @dodo forked pem to add support for altNames. The [PR](https://github.com/andris9/pem/pull/10) was sent and merged.

Since then node-xmpp has been using [dodo's fork](https://github.com/dodo/pem). I just tried replacing with upstream and our test is now failing.

https://github.com/node-xmpp/node-xmpp/blob/master/test/tls-test.js

I had a quick look but I couldn't find anything wrong and my knowledge on the subject is pretty limited.

Any idea?

**Comment by Dexus** [comment]
Hi @sonnyp, I will try and looking into it on weekend.

**Comment by Dexus** [comment]
oh, i see: if you replace the dodo's fork with our upstream you need to change your altNames by only use hostnames and ip address in plain without `DNS =` or `IP =`.

Regards

**Comment by sonnyp** [comment]
@Dexus cool, thanks! https://github.com/node-xmpp/node-xmpp/pull/290
