### ISSUE TITLE
CSR generation fails on empty altNames arrays

### ISSUE THREAD

**Issue by nickdaugherty** [Dexus/pem#77]
If passed an empty array of altNames, pem tries to generate the openssl config, but since there are no names, an open ssl error is produced:

```
Error Loading extension section v3_req
X509 V3 routines:DO_EXT_NCONF:invalid extension string:v3_conf.c:139:name=subjectAltName,section=@alt_names
X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:93:name=subjectAltName, value=@alt_names
```

https://github.com/andris9/pem/blob/e7f9fbae5a4bea25a9c2bc858ec53fd070bf37d4/lib/pem.js#L189

**Comment by DullReferenceException** [comment]
Has this been published yet? I'm seeing the last publish date as occurring before this change. We seem to be impacted by this same bug, and we'd love to have the fix.
