### ISSUE TITLE
Support for "DC" in certificate subject/issuer

### ISSUE THREAD

**Issue by hkoch78** [Dexus/pem#83]
Hello,

the attribute "DC" is not supported by the function "fetchCertificateData". 
The attached ZIP contains a certificate of BMW with the following subject:
  /DC=corp/DC=bmw/DC=europe/CN=BMW Group Issuing CA 3

[seon_TSL_certificate_3pPahZ.cer.zip](https://github.com/andris9/pem/files/375487/seon_TSL_certificate_3pPahZ.cer.zip)

**Comment by hkoch78** [comment]
I've created a patch against 1.8.3 on my own in order to support single "DC" occurances (which is not optimal, but better than nothing). You may include this into future build of pem.js.

[pem.js.patch.zip](https://github.com/andris9/pem/files/375496/pem.js.patch.zip)

**Comment by Dexus** [comment]
Thank you, i will looking into it and try to integrate it.
