### ISSUE TITLE
Certificate serial number clarification

### ISSUE THREAD

**Issue by vstirbu** [Dexus/pem#84]
Can you provide more rationale behind the [serial number function](https://github.com/andris9/pem/blob/master/lib/pem.js#L310). Seems that there are more constraints than required for an ordinary [X509 certificate](https://tools.ietf.org/html/rfc5280#section-4.1.2.2), which only mandates the serial number to be an positive integer less than 20 octets. Thanks!

**Comment by Dexus** [comment]
Hello @vstirbu,

it was a PR that was looking at that time right.

But if you think it need a fix you are welcome to open a PR. (Please use therefor the new URL: github.com/Dexus/pem) Thank you.

**Comment by vstirbu** [comment]
Thanks @Dexus  for taking over the maintenance of the project. I'll open some PRs to the new repo in a couple of days.

**Comment by Dexus** [comment]
@vstirbu you are welcome. I'm happy to see the community get involved with there PR's.
