### ISSUE TITLE
Pull request - new feature libressl support

### ISSUE THREAD

**Issue by simon-p-r** [Dexus/pem#88]
Would you be interested in supporting libressl and windows?  Currently generate key function fails due to different args and your tests fails on my windows box.  If interested I will do a PR for changes.

**Comment by Dexus** [comment]
Hey @simon-p-r,

thank you. I'll happy to see you PR. Please use github.com/Dexus/pem for your PR.

Thank you.

**Comment by simon-p-r** [comment]
I think this would require a major rewrite to module so I am closing due to lack of time.
