### ISSUE TITLE
Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [Dexus/pem#89]
On `node@7.0.0` when [`fs.unlink`](https://nodejs.org/api/fs.html#fs_fs_unlink_path_callback) is invoked.  I think you're supposed to use [`fs.unlinkSync`](https://nodejs.org/api/fs.html#fs_fs_unlinksync_path).

**Comment by sholladay** [comment]
Sync would work. Could also just use a noop callback to avoid blocking the event loop.

**Comment by vizo** [comment]
PR https://github.com/andris9/pem/pull/91

**Comment by wtgtybhertgeghgtwtg** [comment]
Closed with #91.
