### ISSUE TITLE
Transfer of this Repo

### ISSUE THREAD

**Issue by Dexus** [Dexus/pem#95]
@andris9 can you transfer the repo to me?

So i don't need to watch both repos and get notice.

Thank you. Regards, Josef

**Comment by andris9** [comment]
Yeah, sure. You do need to delete your fork before I can transfer the current one as multiple repos with the same name are not allowed (You might be able to rename it as well instead of deleting, I'm not sure). Let me know once you have deleted it and I'll start the transfer process

**Comment by andris9** [comment]
Btw if you have pending changes in your fork then make a PR from your repo to this and merge this PR, otherwise you might lose these changes.

**Comment by Dexus** [comment]
I have pushed and deleted my fork.

Thank you.
