### ISSUE TITLE
Windows support: Windows openssl binaries use ' = ' instead of '=', breaking scraping

### ISSUE THREAD

**Issue by mikemaccana** [Dexus/pem#97]
The [Shining Light Productions](https://slproweb.com/products/Win32OpenSSL.html) Win32 openssl binaries use a slightly different formatting for separating fields in the `Subject`

## Windows

    ~\Documents\foocorp\node_modules\pem $ openssl req -text -noout -verify -in ..\..\deleteme.csr
    verify OK
    Certificate Request:
        Data:
            Version: 1 (0x0)
            Subject: C = GB, L = London, O = foocorp Limited, CN = ssltest.foocorp.com

## Unix

    [mike@a foocorp]$ openssl req -text -noout -verify -in deleteme.csr
    verify OK
    Certificate Request:
        Data:
            Version: 0 (0x0)
            Subject: C=GB, L=London, O=foocorp Limited, CN=ssltest.foocorp.com

Meaning `npm test` fails on Windows. I'm not sure why but it's an easy fix. Sending a PR.

**Comment by Dexus** [comment]
Will not support that because its not a current version.(2004) as i can see.

Von meinem iPhone gesendet

**Comment by mikemaccana** [comment]
Issue is occurring on `OpenSSL 1.1.0c  10 Nov 2016` - not sure where you got 2004 from.     

    ~\Documents\foocorp $ openssl req -text -noout -verify -in .\deleteme.csr                                                                      
    Can't open C:\Program Files\OpenSSL\bin\openssl.cfg for reading, No such file or directory                                                        
    15860:error:02001003:system library:fopen:No such process:crypto\bio\bss_file.c:74:fopen('C:\Program Files\OpenSSL\bin\openssl.cfg','r')          
    15860:error:2006D080:BIO routines:BIO_new_file:no such file:crypto\bio\bss_file.c:81:                                                             
    verify OK                                                                                                                                         
    Certificate Request:                                                                                                                              
        Data:                                                                                                                                         
            Version: 1 (0x0)                                                                                                                          
            Subject: C = GB, L = London, O = foocorp Limited, CN = ssltest.foocorp.com                                                          
            Subject Public Key Info:                                                                                                                  
                Public Key Algorithm: rsaEncryption                                                                                                   
                    Public-Key: (2048 bit)                                                                                                            
                    Modulus:                                                                                                                          
                        00:df:75:96:25:eb:1c:0d:7f:24:d3:5f:42:64:dc:                                                                                 
                        4d:fd:69:ae:d3:00:ac:4b:26:9d:f7:53:bf:ef:cb:                                                                                 
                        ed:c8:6c:4e:91:ac:e0:48:20:7a:ad:11:1e:62:63:                                                                                 
                        e4:26:eb:cc:5d:e2:4f:3f:ed:65:0e:2f:f3:02:65:                                                                                 
                        a3:93:65:2d:cb:84:c4:61:4a:29:66:1f:c1:64:58:                                                                                 
                        4a:88:5e:69:b6:0d:86:67:ca:a5:a3:7f:6e:3a:b9:                                                                                 
                        1c:5b:03:ec:be:f8:f6:25:b7:47:34:ac:b0:99:e8:                                                                                 
                        82:bc:15:71:3f:a0:6f:5a:c7:22:70:70:9d:82:34:                                                                                 
                        ae:37:0f:5e:8a:b6:89:6e:44:9d:e0:52:68:2a:5a:                                                                                 
                        48:b6:c5:2c:96:95:e1:14:b2:ef:74:93:6b:3b:77:                                                                                 
                        09:9a:c2:ef:27:f7:36:61:ea:cf:d9:f3:91:e3:75:                                                                                 
                        52:f5:a6:a7:58:dd:44:74:aa:70:3d:49:1b:cf:0f:                                                                                 
                        bf:86:ea:46:81:71:a4:53:d3:8e:f5:ec:92:aa:f6:                                                                                 
                        98:78:81:3b:83:32:b4:43:cf:67:0e:4f:91:e2:9e:                                                                                 
                        e0:fc:db:38:18:9a:00:de:12:fc:52:6a:bf:ab:64:                                                                                 
                        cf:f9:bb:cf:94:2a:02:64:f1:64:96:6b:7e:42:fd:                                                                                 
                        21:d6:32:12:b5:ad:22:fe:57:e6:3b:2a:b5:c1:5f:                                                                                 
                        01:9f                                                                                                                         
                    Exponent: 65537 (0x10001)                                                                                                         
            Attributes:                                                                                                                               
                a0:00                                                                                                                                 
        Signature Algorithm: sha256WithRSAEncryption                                                                                                  
             b0:31:6d:12:ba:2a:2f:71:7c:ba:35:31:cd:f1:c1:ae:b1:f9:                                                                                   
             41:87:73:b7:10:88:76:d7:1a:bd:4a:ab:9e:06:b6:73:ea:7d:                                                                                   
             d2:47:76:c0:f6:2e:0c:91:6b:04:ab:60:c5:3e:42:f8:eb:5d:                                                                                   
             67:62:bb:98:07:2e:f8:5b:3b:e7:ba:4f:c5:e7:8c:4d:90:75:                                                                                   
             c7:b2:38:85:d8:7e:7f:75:6f:77:5d:bc:c4:85:7f:f6:d0:6d:                                                                                   
             b0:79:91:87:ab:1f:73:4c:eb:5c:40:6b:36:4c:b9:aa:d2:56:                                                                                   
             ad:c2:05:1f:75:33:78:ce:3f:f3:06:ea:5e:61:6d:57:31:05:                                                                                   
             84:e5:c9:e2:e5:ad:9f:ee:d1:c5:9b:c2:42:e8:de:8c:b8:70:                                                                                   
             7d:4e:3a:eb:fe:2c:c9:3a:ef:2f:5c:ed:bf:5d:30:e3:40:1f:                                                                                   
             fd:e4:b2:43:75:b5:db:48:d8:49:50:28:0e:99:32:0d:88:2c:                                                                                   
             90:50:7c:a9:9f:2f:61:59:4f:0e:29:a6:0f:78:5b:97:b0:24:                                                                                   
             98:9e:3e:8e:19:c6:7d:4d:12:a2:03:78:1c:af:f4:94:18:6d:                                                                                   
             f8:d3:a0:5b:6d:26:40:a0:42:17:80:ce:fc:ff:f0:1d:ff:65:                                                                                   
             2a:ed:41:86:e7:aa:ca:62:d6:63:97:3e:66:1e:ca:43:57:a0:                                                                                   
             3c:ab:eb:b1                                                                                                                              

    ~\Documents\foocorp $ openssl version                                                                                                          
    OpenSSL 1.1.0c  10 Nov 2016

**Comment by mikemaccana** [comment]
Oh wait: the copyright notice. Yeah the Shining Light website has an out of date copyright notice, I told the maintainer about it (and the mixed content issue) and he got really angry at me in response. 

Despite that, the site does actually maintain up-to-date openssl binaries.

**Comment by Dexus** [comment]
Thanks, i was only check it short by smartphone. Have merged it.
