### ISSUE TITLE
SubjectAltName attribute in CSR not copied to signed certificate

### ISSUE THREAD

**Issue by jbemmel** [Dexus/pem#99]
While the NodeJS pem API allows one to specify a 'Subject Alternative Name' for a CSR through the 'altNames' parameter, any such value ( IP or DNS ) gets stripped by openssl.

The reason is that 'openssl x509' is used instead of 'openssl ca' for signing the certificate

**Comment by ghost** [comment]
Any updates here?

**Comment by spencerbeggs** [comment]
With Chrome 58, this is starting to throw errors in my development env when I try to output a cert with a trusted PRM. I am investigating, but I am not an SSL pro.

**Comment by phsstory** [comment]
Now that Chrome 58 is the stable release, this library is no longer capable of generating valid certs from CSRs with alt names for chrome environments.

**Comment by Dexus** [comment]
PRs are welcome. Else you have to wait until i have the time to change this.

**Comment by phsstory** [comment]
I mainly commented to get notification when it was fixed, but my work around involved adding a call to readCertificateInfo and checking for a info.san.dns, if found setting the options.config to the example in the readme.

```
[req]
req_extensions = v3_req

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[alt_names]
```

and then 
```
options.config += csr.info.san.dns.map(function(dns, i) { 
  return 'DNS.'+ i + ' = ' + dns; 
}).join('\n');
```
before the call to createCertificate

This solution only works because I control the CSRs and don't have any other createCertificate options in use.

**Comment by Dexus** [comment]
A other way is:

```
[ alternate_names ]
DNS.1        = example.com
DNS.2        = www.example.com
DNS.3        = mail.example.com
DNS.4        = ftp.example.com
IP.1 = 192.168.7.1
IP.2 = 127.0.0.1
IP.3 = 13::17

[ v3_ca ]
subjectAltName      = @alternate_names
keyUsage = digitalSignature, keyEncipherment

[ CA_default ]
copy_extensions = copy
```

set the 
```
[ CA_default ]
copy_extensions = copy
```

we will support this in one of the next versions.

**Comment by AuspeXeu** [comment]
Running into the same issues. Any chance for a fix on this?

**Comment by ranadewa** [comment]
Facing the same issue. Any update on this?

**Comment by Dexus** [comment]
With release of 1.14.0 SAN Certificates will be created from CSR.
